CREATE TABLE EMP08 AS SELECT * FROM EMP;
COL TABLE_NAME FORMAT A15;
COL COLUMN_NAME FORMAT A15;

SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME 
FROM USER_IND_COLUMNS WHERE TABLE_NAME IN('EMP', 'EMP08');

INSERT INTO EMP08 SELECT * FROM EMP08;

INSERT INTO EMP08 (EMPNO, ENAME) VALUES(1111, 'MJS');

SET TIMING ON;

SELECT DISTINCT EMPNO, ENAME FROM EMP08 WHERE ENAME='MJS';

CREATE INDEX IDX_EMP08_ENAME ON EMP08(ENAME);

SELECT TABLE_NAME, INDEX_NAME 
FROM USER_INDEXES WHERE TABLE_NAME IN('EMP08');

SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME 
FROM USER_IND_COLUMNS WHERE TABLE_NAME IN('EMP08');

SELECT DISTINCT EMPNO, ENAME FROM EMP08 WHERE ENAME='MJS';

drop index idx_emp08_ename;

select table_name, index_name
from user_indexes
where table_name in ('emp08');


